// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC1DHaV5QN5-4eE96EP2lYBaEYo-vTUCk',
    appId: '1:1078593702300:web:19d53fdebe9b94b6786059',
    messagingSenderId: '1078593702300',
    projectId: 'cards-da774',
    authDomain: 'cards-da774.firebaseapp.com',
    storageBucket: 'cards-da774.firebasestorage.app',
    measurementId: 'G-6VQ53VNKLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhFgPcgITGxFwLlTdPCHg87UfgwOxcBfw',
    appId: '1:1078593702300:android:e61a514fd58b44ab786059',
    messagingSenderId: '1078593702300',
    projectId: 'cards-da774',
    storageBucket: 'cards-da774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdfJexN4Uqgkr9pzEySCr6MBwoLMkdTkw',
    appId: '1:1078593702300:ios:d721b6bdfe26d234786059',
    messagingSenderId: '1078593702300',
    projectId: 'cards-da774',
    storageBucket: 'cards-da774.firebasestorage.app',
    iosBundleId: 'ca.sparkandspiral.dailysolitaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdfJexN4Uqgkr9pzEySCr6MBwoLMkdTkw',
    appId: '1:1078593702300:ios:d721b6bdfe26d234786059',
    messagingSenderId: '1078593702300',
    projectId: 'cards-da774',
    storageBucket: 'cards-da774.firebasestorage.app',
    iosBundleId: 'ca.sparkandspiral.dailysolitaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC1DHaV5QN5-4eE96EP2lYBaEYo-vTUCk',
    appId: '1:1078593702300:web:ee605be149bc6d4e786059',
    messagingSenderId: '1078593702300',
    projectId: 'cards-da774',
    authDomain: 'cards-da774.firebaseapp.com',
    storageBucket: 'cards-da774.firebasestorage.app',
    measurementId: 'G-3TY7X4J6MQ',
  );
}
